# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brownpapertickets}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alvaro Insignares"]
  s.date = %q{2011-02-16}
  s.description = %q{Brown Paper tickets API wrapper}
  s.email = %q{alvaro@koombea.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "README.rdoc"
  ]
  s.files = [
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "brownpapertickets/.document",
    "brownpapertickets/.gitignore",
    "examples/create_item.rb",
    "examples/fetch_items.rb",
    "examples/update_item.rb",
    "lib/brownpapertickets.rb",
    "lib/brownpapertickets/base.rb",
    "lib/brownpapertickets/date.rb",
    "lib/brownpapertickets/price.rb",
    "lib/brownpapertickets/event.rb",
    "lib/brownpapertickets/httpost.rb",
    "lib/brownpapertickets/xmlparse.rb",
    "spec/brownpapertickets_spec.rb",
    "spec/fixtures/all_events.xml",
    "spec/fixtures/create_not_ok.xml",
    "spec/fixtures/create_ok.xml",
    "spec/fixtures/event.xml",
    "spec/fixtures/test.json",
    "spec/fixtures/update_not_ok.xml",
    "spec/fixtures/update_ok.xml",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bbto/brownpapertickets}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Brown Paper tickets API wrapper}
  s.test_files = [
    "examples/create_item.rb",
    "examples/fetch_items.rb",
    "examples/update_item.rb",
    "spec/brownpapertickets_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, ["~> 1.2.0"])
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, ["~> 1.2.0"])
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
  end
end

